### ISSUE TITLE
Can't use with PKG - conflict with documentation

### ISSUE THREAD

**Issue by JacobWrenn** [cryptlex/lexactivator-js#10]
The docs over at <https://docs.cryptlex.com/node-locked-licenses/using-lexactivator/using-lexactivator-with-node.js> say:
> In order to package your Node.js project into an executable, check out pkg project.

However, this clearly isn't possible as PKG does not allow .node files like those used by lexactivator to be compiled into the binary.

Did this used to be available on an older version or do you have a custom solution?

**Comment by adnan-kamili** [comment]
Hi Jacob,

You need to ship the .node files along with your exe/binary file. This is how it works in the case of pkg.

**Comment by JacobWrenn** [comment]
Thanks Adnan. Do you have any advice on extracting the .node files out of node_modules so that they can be shipped? For example in a CI/CD situation

**Comment by JacobWrenn** [comment]
I only ask because pkg does not provide a guide on how to achieve this but your documentation implies it is simple to use your software with pkg

**Comment by adnan-kamili** [comment]
After npm i just invoke the following command:

`cp -a  node_modules/@cryptlex/lexactivator/lib/binding/**/ ./`

**Comment by JacobWrenn** [comment]
Brilliant, thanks!

**Comment by DrewImm** [comment]
Is there a workaround for AndroidJS?

Built node library is for linux, APK searches for android.

Is Android supported? How can Android support be added?
