### ISSUE TITLE
Missing LexErrorCodes from module export

### ISSUE THREAD

**Issue by robertsLando** [cryptlex/lexactivator-js#2]
After the update `LexStatusCodes` only contains status codes and there is no way to access error codes contained in `lexactivator-exception.js`. T
hey are needed for example in licenseCallback to handle status changes and should be exported in the `index.js` like `LexStatusCodes`. 

My suggestion is to create an universal function `getStatusMessage` that returns the message of the error/status from the code, something like the one inside `lexactivator-exception.js` function `getErrorMessage` but with status support too.

**Comment by adnan-kamili** [comment]
Please check out following example:

https://github.com/cryptlex/lexactivator-js/blob/master/examples/sample.js#L34
