### ISSUE TITLE
[feat] Typescript support

### ISSUE THREAD

**Issue by robertsLando** [cryptlex/lexactivator-js#32]
Could you add some types please?

**Comment by robertsLando** [comment]
any news on this? 

@ahmad-kemsan

**Comment by adnan-kamili** [comment]
@azan-n Please add the typings

**Comment by adnan-kamili** [comment]
@robertsLando done

**Comment by robertsLando** [comment]
Thanks! 🙏🏼

**Comment by robertsLando** [comment]
@adnan-kamili This specific commit: https://github.com/cryptlex/lexactivator-js/commit/2085835e8518fecd42dcf24a054d8121c31a74cd#diff-45e96039b1f6b3afb46b650541cf676aad1ec7954302df30806f6266ae19fa6cL7

Broke my server error handling logic as now `code` [doesn't exist](https://github.com/cryptlex/lexactivator-js/blob/master/src/lexactivator-exception.ts#L6) as property anymore. Would it be possible to restore it please?

**Comment by azan-n** [comment]
> @adnan-kamili This specific commit: [2085835#diff-45e96039b1f6b3afb46b650541cf676aad1ec7954302df30806f6266ae19fa6cL7](https://github.com/cryptlex/lexactivator-js/commit/2085835e8518fecd42dcf24a054d8121c31a74cd#diff-45e96039b1f6b3afb46b650541cf676aad1ec7954302df30806f6266ae19fa6cL7)
> 
> Broke my server error handling logic as now `code` [doesn't exist](https://github.com/cryptlex/lexactivator-js/blob/master/src/lexactivator-exception.ts#L6) as property anymore. Would it be possible to restore it please?
> 
> cc @azan-n @ahmad-kemsan

I apologize for this mistake. I'll push a quick fix just now.

**Comment by adnan-kamili** [comment]
@robertsLando Please update to the latest version, the issue is fixed now.

**Comment by robertsLando** [comment]
Thanks for the quick fix 🙏🏼
